line = "JG ZPV'SF B UIBOLTHJWJOH EJOOFS, CVU ZPV EPO'U MJLF UIF TUVGGJOH PS UIF DSBOCFSSZ TBVDF PS BOZUIJOH FMTF, KVTU QSFUFOE MJLF ZPV'SF FBUJOH JU, CVU JOTUFBE, QVU JU BMM JO ZPVS MBQ BOE GPSN JU JOUP B CJH NVTIZ CBMM. UIFO, MBUFS, XIFO ZPV'SF PVU CBDL IBWJOH DJHBST XJUI UIF CPZT, MFU PVU B CJH GBLF DPVHI BOE UISPX UIF CBMM UP UIF HSPVOE. UIFO TBZ, \"CPZ, UIFTF BSF HPPE DJHBST!\""
line = "TEBK QEB XDB LC QEB SFHFKDP ZXJB QL X ZILPB, QEBV JRPQ EXSB PBKPBA FQ. MOLYXYIV, QEB DXQEBOBA QLDBQEBO LKB BSBKFKD, PIXMMBA BXZE LQEBO LK QEB YXZH XKA PXFA, \"EBV, DLLA GLY.\""

import sys

for i in line:
    if ord(i) >=65 and ord(i)<=90:
        i = ord(i) - 65
        i = (i - 23) % 26

        sys.stdout.write(chr(i+65))
    else:
        sys.stdout.write(i)
    